name: Build LaTeX documents and Generate README
on: [push]
jobs:
  build_latex_and_readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Check for changes in dl.tex
        id: check_dl
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^dl\.tex$'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Check for changes in main.tex
        id: check_main
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^main\.tex$'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Compile dl.tex
        if: steps.check_dl.outputs.changed == 'true'
        uses: xu-cheng/latex-action@v3
        with:
          root_file: dl.tex
          args: -pdf -file-line-error -interaction=nonstopmode -shell-escape

      - name: Compile main.tex
        if: steps.check_main.outputs.changed == 'true'
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          args: -pdf -file-line-error -interaction=nonstopmode -shell-escape

      - name: Get current date
        id: date
        if: steps.check_dl.outputs.changed == 'true' || steps.check_main.outputs.changed == 'true'
        run: echo "date=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT

      - name: Upload PDFs to book branch
        if: steps.check_dl.outputs.changed == 'true' || steps.check_main.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          if git show-ref --verify --quiet refs/remotes/origin/book; then
            git checkout book
          else
            git checkout --orphan book
            git rm -rf .
          fi
          
          find . -maxdepth 1 -name "*.pdf" -type f -exec cp {} . \; || echo "No PDFs found"
          
          if ls *.pdf 1> /dev/null 2>&1; then
            git add *.pdf
            git commit -m "ðŸš€ Update PDFs - ${{ steps.date.outputs.date }}"
            git push origin book
          else
            echo "No PDFs to commit"
          fi

      - name: Upload PDFs as artifacts
        if: steps.check_dl.outputs.changed == 'true' || steps.check_main.outputs.changed == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: PDFs
          path: "*.pdf"
          if-no-files-found: warn
